parameters:
    dcms_theme.menu.class: DCMS\Bundle\ThemeBundle\Menu\ThemeMenu

services:
    dcms_theme.menu:
        class: %dcms_theme.menu.class%
        tags:
            - { name: kernel.event_listener, event: dcms_admin.menu_extend, method: extendMenu }
