services:
    dcms_theme.twig.extension:
        class: DCMS\Bundle\ThemeBundle\Twig\Extension\ThemeExtension
        arguments:
            - @dcms_theme.template_manager
        tags:
            - { name: twig.extension }

    dcms_theme.twig.document_loader:
        class: DCMS\Bundle\ThemeBundle\Twig\DocumentLoader
        arguments:
            - @dcms_theme.repository.template

    dcms_theme.twig.chain_loader:
        class: Twig_Loader_Chain
        arguments:
            - [ @dcms_theme.twig.document_loader, @twig.loader.filesystem ]
