dcms_markdown:
    resource: "@DCMSMarkdownBundle/Controller/"
    type:     annotation
    prefix:   /

dcms_admin:
    resource: "@DCMSAdminBundle/Controller/"
    type:     annotation
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
