dcms_blog:
    resource: "@DCMSBlogBundle/Controller/"
    type:     annotation
    prefix:   /admin/

dcms_menu:
    resource: "@DCMSMenuBundle/Controller/"
    type:     annotation
    prefix:   /admin/

dcms_core:
    resource: "@DCMSCoreBundle/Controller/"
    type:     annotation
    prefix:   /admin/

dcms_markdown:
    resource: "@DCMSMarkdownBundle/Controller/"
    type:     annotation
    prefix:   /admin/

dcms_admin:
    resource: "@DCMSAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin/

dcms_theme:
    resource: "@DCMSThemeBundle/Controller/"
    type:     annotation
    prefix:   /admin/theme

#_proxy:
#    resource: "@FrameworkBundle/Resources/config/routing/proxy.xml"
#    prefix:   /_proxy
# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
