dcms_blog:
    resource: "@DCMSBlogBundle/Controller/"
    type:     annotation
    prefix:   /admin/

dcms_menu:
    resource: "@DCMSMenuBundle/Controller/"
    type:     annotation
    prefix:   /admin/

dcms_core:
    resource: "@DCMSCoreBundle/Controller/"
    type:     annotation
    prefix:   /admin/

dcms_markdown:
    resource: "@DCMSMarkdownBundle/Controller/"
    type:     annotation
    prefix:   /admin/

dcms_admin:
    resource: "@DCMSAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin/

dcms_theme:
    resource: "@DCMSThemeBundle/Controller/"
    type:     annotation
    prefix:   /admin/theme

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /sonata

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /sonata

phpcrbrowser:
    resource: @SymfonyCmfTreeBrowserBundle/Resources/config/routing/phpcrbrowser.xml
    prefix: /admin/browser

phpcrodmbrowser:
    resource: @SonataDoctrinePHPCRAdminBundle/Resources/config/routing/phpcrodmbrowser.xml
    prefix: /admin/browser

#_proxy:
#    resource: "@FrameworkBundle/Resources/config/routing/proxy.xml"
#    prefix:   /_proxy
# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
