dcms_menu:
    resource: "@DCMSMenuBundle/Controller/"
    type:     annotation
    prefix:   /

dcms_core:
    resource: "@DCMSCoreBundle/Controller/"
    type:     annotation
    prefix:   /

dcms_markdown:
    resource: "@DCMSMarkdownBundle/Controller/"
    type:     annotation
    prefix:   /

dcms_admin:
    resource: "@DCMSAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin/

dcms_theme:
    resource: "@DCMSThemeBundle/Controller/"
    type:     annotation
    prefix:   /admin/theme

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
